/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as DashIndexRouteImport } from './routes/_dash.index'
import { Route as DashQuestionBankRouteImport } from './routes/_dash.question-bank'
import { Route as DashHistoryRouteImport } from './routes/_dash.history'
import { Route as DashExamsRouteImport } from './routes/_dash.exams'

const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashQuestionBankRoute = DashQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => DashRoute,
} as any)
const DashHistoryRoute = DashHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashRoute,
} as any)
const DashExamsRoute = DashExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashIndexRoute
  '/exams': typeof DashExamsRoute
  '/history': typeof DashHistoryRoute
  '/question-bank': typeof DashQuestionBankRoute
}
export interface FileRoutesByTo {
  '/exams': typeof DashExamsRoute
  '/history': typeof DashHistoryRoute
  '/question-bank': typeof DashQuestionBankRoute
  '/': typeof DashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dash': typeof DashRouteWithChildren
  '/_dash/exams': typeof DashExamsRoute
  '/_dash/history': typeof DashHistoryRoute
  '/_dash/question-bank': typeof DashQuestionBankRoute
  '/_dash/': typeof DashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exams' | '/history' | '/question-bank'
  fileRoutesByTo: FileRoutesByTo
  to: '/exams' | '/history' | '/question-bank' | '/'
  id:
    | '__root__'
    | '/_dash'
    | '/_dash/exams'
    | '/_dash/history'
    | '/_dash/question-bank'
    | '/_dash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/': {
      id: '/_dash/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/question-bank': {
      id: '/_dash/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof DashQuestionBankRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/history': {
      id: '/_dash/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof DashHistoryRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/exams': {
      id: '/_dash/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof DashExamsRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashExamsRoute: typeof DashExamsRoute
  DashHistoryRoute: typeof DashHistoryRoute
  DashQuestionBankRoute: typeof DashQuestionBankRoute
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashExamsRoute: DashExamsRoute,
  DashHistoryRoute: DashHistoryRoute,
  DashQuestionBankRoute: DashQuestionBankRoute,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
